// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polizia_Municipale.Models.Entities;

#nullable disable

namespace Polizia_Municipale.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205094534_ss")]
    partial class ss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Anagrafica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnagraficaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnagraficaId");

                    b.ToTable("Anagrafiche");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Verbale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnagraficaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataTrascrizioneVerbale")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataViolazione")
                        .HasColumnType("date");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NominativoAgente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ViolazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnagraficaId");

                    b.HasIndex("ViolazioneId");

                    b.ToTable("Verbali");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Violazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Violazioni");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Anagrafica", b =>
                {
                    b.HasOne("Polizia_Municipale.Models.Entities.Anagrafica", null)
                        .WithMany("Anagrafiche")
                        .HasForeignKey("AnagraficaId");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Verbale", b =>
                {
                    b.HasOne("Polizia_Municipale.Models.Entities.Anagrafica", "Anagrafica")
                        .WithMany()
                        .HasForeignKey("AnagraficaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Polizia_Municipale.Models.Entities.Violazione", "Violazione")
                        .WithMany("Verbali")
                        .HasForeignKey("ViolazioneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Anagrafica");

                    b.Navigation("Violazione");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Anagrafica", b =>
                {
                    b.Navigation("Anagrafiche");
                });

            modelBuilder.Entity("Polizia_Municipale.Models.Entities.Violazione", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
